# Generated by Django 6.0.5 on 2026-07-05 23:31

import apps.purchases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Actual date of purchase')),
                ('shipping_code', models.CharField(default=apps.purchases.models.generate_shipping_code, help_text='Auto-generated unique shipping/batch code', max_length=20, unique=True)),
                ('currency', models.CharField(default='ETB', help_text='Currency used for this purchase', max_length=10)),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all item amounts. Auto-updated when items change.', max_digits=15)),
                ('amount_paid_now', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to factory at purchase time. 0 = buy on credit. Any amount = reduces what you owe.', max_digits=15)),
                ('unpaid_amount', models.DecimalField(decimal_places=2, default=0, help_text='total_purchase_amount - amount_paid_now. This amount is added to factory balance.', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('factory', models.ForeignKey(help_text='Which factory this purchase is from', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(help_text='Product code typed freely. Example: SOCK-ANKLE-01', max_length=100)),
                ('product_name', models.CharField(help_text='Human readable product name', max_length=255)),
                ('price_type', models.CharField(choices=[('per_piece', 'Price Per Piece'), ('per_bag', 'Price Per Bag')], default='per_piece', help_text='Is the price per single piece or per whole bag?', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost price per piece OR per bag depending on price_type', max_digits=15)),
                ('pcs_per_bag', models.PositiveIntegerField(help_text='How many pieces in ONE bag. Example: 24 means one bag contains 24 pieces. This is critical for stock and sales calculations.')),
                ('total_bags_purchased', models.PositiveIntegerField(help_text='How many bags were purchased')),
                ('total_pieces_purchased', models.PositiveIntegerField(default=0, help_text='Auto calculated: total_bags × pcs_per_bag')),
                ('total_item_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated total cost for this product line', max_digits=15)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('purchase', models.ForeignKey(help_text='The purchase order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'ordering': ['item_code'],
            },
        ),
    ]
