# Generated by Django 6.0.5 on 2026-07-11 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Actual date of purchase'),
        ),
    ]
