# Generated by Django 6.0.5 on 2026-07-05 23:31

import apps.sales.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Actual sale date')),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('partial', 'Partial Payment')], default='cash', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('telebirr', 'Telebirr'), ('cbe', 'CBE'), ('boa', 'BOA'), ('awash', 'Awash'), ('other', 'Other')], help_text='Payment method used (CBE, Telebirr, etc.)', max_length=20, null=True)),
                ('amount_paid_now', models.DecimalField(decimal_places=2, default=0, help_text='Cash received at sale time. 0 for full credit. Full amount for cash. Any amount in between for partial.', max_digits=15)),
                ('total_sale_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all items. Auto-updated when items change.', max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount added to customer balance. = total_sale_amount - amount_paid_now', max_digits=15)),
                ('invoice_number', models.CharField(default=apps.sales.models.generate_invoice_number, help_text='Auto-generated invoice number', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(help_text='Customer making the purchase', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bags_sold', models.DecimalField(decimal_places=2, help_text='Number of bags sold from this batch', max_digits=10)),
                ('pcs_per_bag', models.PositiveIntegerField(help_text='Copied from batch at sale time. Locked for history.')),
                ('pieces_sold', models.PositiveIntegerField(default=0, help_text='Auto calculated: bags_sold × pcs_per_bag')),
                ('sell_price_type', models.CharField(choices=[('per_piece', 'Price Per Piece'), ('per_bag', 'Price Per Bag')], default='per_piece', help_text='Is the selling price per piece or per bag?', max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per piece OR per bag', max_digits=15)),
                ('total_line_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated total for this line', max_digits=15)),
                ('purchase_cost_per_piece', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of batch cost per piece at sale time', max_digits=15)),
                ('sale', models.ForeignKey(help_text='The sale invoice this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('stock_batch', models.ForeignKey(help_text='Which stock batch (shipment) is being sold from', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.stockbatch')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'ordering': ['stock_batch__item_code'],
            },
        ),
    ]
