# Generated by Django 6.0.5 on 2026-07-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name or business name', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Main contact number', max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text='City, area, or shop location', max_length=255, null=True)),
                ('initial_credit', models.DecimalField(decimal_places=2, default=0, help_text='Debt this customer had BEFORE the app was used. Added to balance from day one.', max_digits=15)),
                ('initial_credit_currency', models.CharField(default='ETB', help_text='Currency of the initial credit amount', max_length=10)),
                ('opening_date', models.DateField(help_text='Date customer was registered')),
                ('is_active', models.BooleanField(default=True, help_text='False means archived/hidden, not deleted')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
