# Generated by Django 6.0.5 on 2026-07-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Business', max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('low_stock_alert_percentage', models.PositiveIntegerField(default=20, help_text='Alert when remaining stock drops below this % of purchased amount')),
                ('default_currency', models.CharField(default='ETB', max_length=10)),
                ('available_currencies', models.JSONField(default=list, help_text="List of currencies owner can use. Example: ['ETB', 'USD']")),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
