# Generated by Django 6.0.5 on 2026-07-05 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(db_index=True, help_text='Product code — same code can exist in multiple batches', max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('shipping_code', models.CharField(db_index=True, help_text='Groups all batches from the same shipment', max_length=20)),
                ('pcs_per_bag', models.PositiveIntegerField(help_text='Pieces per bag for THIS batch. Critical for sales: 3 bags × 24 pcs = 72 pieces')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost price from purchase (per piece or per bag)', max_digits=15)),
                ('price_type', models.CharField(choices=[('per_piece', 'Per Piece'), ('per_bag', 'Per Bag')], default='per_piece', max_length=10)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('total_bags_purchased', models.PositiveIntegerField(help_text='Starting bag count — never changes after creation')),
                ('total_pieces_purchased', models.PositiveIntegerField(help_text='Starting piece count — never changes after creation')),
                ('sold_bags', models.DecimalField(decimal_places=2, default=0, help_text='Bags sold so far. Increases with every sale from this batch.', max_digits=10)),
                ('sold_pieces', models.PositiveIntegerField(default=0, help_text='Pieces sold so far. Increases with every sale from this batch.')),
                ('factory', models.ForeignKey(help_text='Which factory supplied this stock', on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='factories.factory')),
                ('purchase', models.ForeignKey(help_text='The purchase order this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='purchases.purchase')),
                ('purchase_item', models.OneToOneField(help_text='The purchase item this stock batch comes from', on_delete=django.db.models.deletion.CASCADE, related_name='stock_batch', to='purchases.purchaseitem')),
            ],
            options={
                'verbose_name': 'Stock Batch',
                'verbose_name_plural': 'Stock Batches',
                'ordering': ['-purchase__date', 'item_code'],
            },
        ),
    ]
