# Generated by Django 6.0.5 on 2026-07-05 23:31

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('factories', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date expense was paid')),
                ('description', models.TextField(help_text='What was this expense for? Write clearly. Example: Monthly warehouse rent')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=15)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr'), ('cbe', 'CBE'), ('boa', 'BOA'), ('awash', 'Awash'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Receipt number or reference, optional', max_length=255, null=True)),
                ('expense_number', models.CharField(help_text='Auto-generated expense reference number', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'General Expense',
                'verbose_name_plural': 'General Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date payment was received')),
                ('paid_amount', models.DecimalField(decimal_places=2, help_text='Amount received from customer', max_digits=15)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr'), ('cbe', 'CBE'), ('boa', 'BOA'), ('awash', 'Awash'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Transaction reference or bank slip number', max_length=255, null=True)),
                ('is_auto', models.BooleanField(default=False, help_text='True = auto-created from sale. False = manually entered by owner.')),
                ('receipt_number', models.CharField(default=apps.payments.models.generate_receipt_number, help_text='Auto-generated receipt number', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the payment', on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='customers.customer')),
                ('sale', models.OneToOneField(blank=True, help_text='Linked sale for auto-created records. Null for manual payments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_income', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Customer Income',
                'verbose_name_plural': 'Customer Incomes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, help_text='Amount paid to factory', max_digits=15)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr'), ('cbe', 'CBE'), ('boa', 'BOA'), ('awash', 'Awash'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_auto', models.BooleanField(default=False, help_text='True = auto-created from purchase. False = manually entered by owner.')),
                ('payment_number', models.CharField(default=apps.payments.models.generate_payment_number, help_text='Auto-generated payment number', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('factory', models.ForeignKey(help_text='Factory that was paid', on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='factories.factory')),
                ('purchase', models.OneToOneField(blank=True, help_text='Linked purchase for auto-created records. Null for standalone payments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_payment', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Factory Payment',
                'verbose_name_plural': 'Factory Payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
